/* EasyMarket compatibility bridge. Sensitive writes go through easymarket-api. */
(function(){
  'use strict';
  const API='https://uhmgjcoyxehknkehfbbj.supabase.co/functions/v1/easymarket-api';
  const U='https://uhmgjcoyxehknkehfbbj.supabase.co';
  const K='sb_publishable_7Bn4Azfm58BkIJS_6vSsUw_qbGS4wTH';
  let db, products=[], cart=[];
  const tg=window.Telegram?.WebApp;
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  async function secure(action,payload={}){const initData=tg?.initData||'';if(!initData)throw Error('Откройте Mini App из Telegram');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload,initData})});const d=await r.json().catch(()=>null);if(!r.ok||!d?.success)throw Error(d?.error||'Ошибка сервера');return d}
  function opts(p){let a=Array.isArray(p.price_options)?p.price_options:[];if(!a.length){const m=String(p.details||'').match(/<!--EM_PRICES:(.*?)-->/);if(m)try{a=JSON.parse(m[1])}catch(_){}}if(!Array.isArray(a)||!a.length)a=[{qty:1,price:+p.price||0}];return a.map(x=>({qty:+x.qty,price:+x.price})).filter(x=>x.qty>0&&x.price>=0)}
  function toast(s){try{window.showToast?.(s);if(!window.showToast&&tg?.showPopup)tg.showPopup({title:'EasyMarket',message:String(s).slice(0,190),buttons:[{id:'ok',type:'ok',text:'OK'}]})}catch(_){} }
  function save(){try{localStorage.setItem('easymarket_cart',JSON.stringify(cart))}catch(_){}}
  function loadCart(){try{const x=JSON.parse(localStorage.getItem('easymarket_cart')||'[]');cart=Array.isArray(x)?x:[]}catch(_){cart=[]}}
  function drawCart(){const box=document.getElementById('cartItems'),total=document.getElementById('cartTotal'),btn=document.getElementById('checkoutButton');if(!box)return;if(!cart.length){box.innerHTML='<div class="empty">Корзина пустая 🛒</div>';if(total)total.textContent='0 ₽';if(btn){btn.disabled=true;btn.textContent='Корзина пустая'}return}let sum=0;box.innerHTML=cart.map((p,i)=>{sum+=+p.price||0;return `<div class="cart-item"><div><div class="cart-item-name">${esc(p.name)}</div><div class="cart-item-price">${+p.price||0} ₽ · ${+p.quantity||1} шт.</div></div><button class="remove-btn" data-em-remove="${i}">✕</button></div>`}).join('');if(total)total.textContent=sum+' ₽';if(btn){btn.disabled=false;btn.textContent='⚡ Оформить заказ'}}
  function addToCartFixed(p,q){const o=opts(p).find(x=>+x.qty===+q)||opts(p)[0];const i=cart.findIndex(x=>+x.id===+p.id);cart[i<0?cart.length:i]={...p,quantity:+o.qty,price:+o.price};save();drawCart();toast('Товар добавлен в корзину 🛒')}
  function openProductFixed(p,q){const modal=document.getElementById('productModal'),content=document.getElementById('productModalContent');if(!modal||!content)return;const list=opts(p),selected=list.find(x=>+x.qty===+q)||list[0];content.innerHTML=(p.image_url?`<img class="product-modal-image" src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<div class="product-modal-icon">${esc(p.icon||'📦')}</div>`)+`<div class="product-modal-title">${esc(p.name)}</div><div class="product-modal-price">${+selected.price||0} ₽</div>${list.length>1?`<div class="quantity-options">${list.map(x=>`<button type="button" class="quantity-option ${+x.qty===+selected.qty?'active':''}" data-em-qty="${x.qty}">${x.qty} шт. <small>${x.price} ₽</small></button>`).join('')}</div>`:''}<div class="product-modal-actions"><button type="button" class="buy-btn" id="em-fixed-buy">⚡ Оформить</button></div>`;modal.classList.add('open');document.body.style.overflow='hidden';content.querySelectorAll('[data-em-qty]').forEach(b=>b.onclick=()=>openProductFixed(p,+b.dataset.emQty));document.getElementById('em-fixed-buy').onclick=()=>{addToCartFixed(p,selected.qty);modal.classList.remove('open');document.body.style.overflow=''}}
  function renderFixed(){const box=document.getElementById('products');if(!box)return;const q=(document.getElementById('searchInput')?.value||'').trim().toLowerCase();const list=products.filter(p=>(!p.seller_id||String(p.approval_status||'approved')==='approved')&&(!q||String(p.name||'').toLowerCase().includes(q)||String(p.description||'').toLowerCase().includes(q)));box.innerHTML=list.length?list.map(p=>`<div class="product" data-em-product="${p.id}">${p.image_url?`<img class="product-image" src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<div class="product-icon">${esc(p.icon||'📦')}</div>`}<div class="product-name">${esc(p.name)}</div><div class="product-description">${esc(p.description||'')}</div><div class="product-bottom"><div class="product-cart-action"><div class="price">${+p.price||0} ₽</div><button class="buy-btn" data-em-buy="${p.id}">⚡ Оформить</button></div></div></div>`).join(''):'<div class="empty">Товары не найдены 📦</div>';box.querySelectorAll('[data-em-product]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-em-buy]'))return;const p=products.find(x=>+x.id===+c.dataset.emProduct);if(p)openProductFixed(p)});box.querySelectorAll('[data-em-buy]').forEach(b=>b.onclick=e=>{e.stopPropagation();const p=products.find(x=>+x.id===+b.dataset.emBuy);if(p)addToCartFixed(p,opts(p)[0].qty)})}
  async function checkoutFixed(){if(!cart.length)return toast('Корзина пустая');try{const r=await secure('create_order',{items:cart.map(p=>({product_id:Number(p.id),quantity:Math.max(1,Math.floor(Number(p.quantity||1)))}))});cart=[];save();drawCart();document.getElementById('cartPanel')?.classList.remove('open');toast('Заказ №'+r.order.id+' создан ✅');tg?.showAlert?.('Заказ №'+r.order.id+' оформлен!')}catch(e){toast(e.message||String(e))}}
  async function start(){loadCart();drawCart();try{db=window.supabase.createClient(U,K);const r=await db.from('products').select('*').order('id',{ascending:false});if(r.error)throw r.error;products=r.data||[];renderFixed()}catch(e){console.error('EasyMarket bridge',e)}document.getElementById('searchInput')?.addEventListener('input',renderFixed);document.addEventListener('click',e=>{const rm=e.target.closest('[data-em-remove]');if(rm){cart.splice(+rm.dataset.emRemove,1);save();drawCart()}if(e.target.id==='checkoutButton')checkoutFixed()},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
  window.emFixed={openProductFixed,addToCartFixed,openCart:()=>document.getElementById('cartPanel')?.classList.add('open'),checkoutFixed};
})();
