/* EasyMarket stable Telegram compatibility layer v20260917-13. */
(function(){
'use strict';
var API='https://uhmgjcoyxehknkehfbbj.supabase.co/functions/v1/easymarket-api';
var SUPABASE_URL='https://uhmgjcoyxehknkehfbbj.supabase.co';
var SUPABASE_KEY='sb_publishable_7Bn4Azfm58BkIJS_6vSsUw_qbGS4wTH';
if(!window.supabaseClient&&window.supabase&&typeof window.supabase.createClient==='function')window.supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
window.emSecureApi=async function(action,payload){var tg=window.Telegram&&window.Telegram.WebApp,initData=tg&&tg.initData||'';if(!initData)throw new Error('Откройте Mini App из Telegram');var response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:action,payload:payload||{},initData:initData})}),data=await response.json().catch(function(){return null});if(!response.ok||!data||data.success===false)throw new Error(data&&data.error||'Ошибка сервера');return data};
function install(){var modal=document.getElementById('productModal');if(modal&&modal.dataset.emGuardInstalled!=='1'){modal.dataset.emGuardInstalled='1';modal.addEventListener('click',function(e){if(e.target!==modal)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(typeof window.closeProductModal==='function')window.closeProductModal();else{modal.classList.remove('open');document.body.style.overflow=''}},true)}}
function getBtn(e){var target=e&&e.target;if(target&&target.nodeType===3)target=target.parentElement;return target&&target.closest?target.closest('#productModal .product-modal-actions .product-buy-now'):null}
function getAction(btn){var code=btn&&btn.getAttribute('onclick')||'',m=code.match(/addToCartFromModal\(\s*(\d+)\s*,\s*(\d+(?:\.\d+)?)\s*\)/);return m?{id:Number(m[1]),qty:Number(m[2])}:null}
function blockPress(e){var btn=getBtn(e);if(!btn)return false;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return true}
function handleModalClick(e){var btn=getBtn(e);if(!btn)return false;var now=Date.now();if(Number(btn.dataset.emHandledAt||0)>now-1000){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return true}var action=getAction(btn);if(!action)return false;btn.dataset.emHandledAt=String(now);e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(typeof window.addToCartFromModal==='function')window.addToCartFromModal(action.id,action.qty);else if(window.showToast)window.showToast('Корзина ещё загружается, попробуйте ещё раз');return true}
window.addEventListener('touchstart',blockPress,true);window.addEventListener('pointerdown',blockPress,true);window.addEventListener('touchend',blockPress,true);window.addEventListener('pointerup',blockPress,true);window.addEventListener('click',handleModalClick,true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
(function(){var style=document.createElement('style');style.id='em-order-cta-label';style.textContent='.product-buy-now{font-size:13px!important}.product-modal-actions .product-buy-now{font-size:0!important}.product-modal-actions .product-buy-now::after{content:"⚡ Оформить заказ";font-size:13px;font-weight:700}.product-modal-actions .product-buy-now{position:relative;z-index:9999;touch-action:manipulation}';(document.head||document.documentElement).appendChild(style)})();
(function(){
'use strict';
function parseOptions(p){var a=Array.isArray(p&&p.price_options)?p.price_options:[];if(!a.length){var m=String(p&&p.details||'').match(/<!--EM_PRICES:([\\s\\S]*?)-->/);if(m)try{a=JSON.parse(m[1])}catch(e){}}if(!Array.isArray(a)||!a.length)a=[{qty:Number(p&&p.stock||1),price:Number(p&&p.price||0)}];return a.filter(function(x){return Number(x.qty)>0&&Number(x.price)>=0}).map(function(x){return {qty:Number(x.qty),price:Number(x.price)}})}
function ensureSellerOptions(){var form=document.getElementById('sellerProductForm');if(!form||document.getElementById('emForcedSellerOptions'))return;var anchor=document.getElementById('sellerProductStock');var wrap=document.createElement('div');wrap.id='emForcedSellerOptions';wrap.style.cssText='display:grid;gap:8px;margin:10px 0;padding:10px;border:1px solid #3b4260;border-radius:12px';wrap.innerHTML='<b>💰 Количество и цена</b><div id="emForcedRows"></div><button type="button" id="emForcedAdd">＋ Добавить вариант</button><small>Укажи количество и цену каждого варианта.</small>';if(anchor&&anchor.parentNode)anchor.parentNode.parentNode.insertBefore(wrap,anchor.parentNode.nextSibling);else form.appendChild(wrap);function add(q,p){var row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:1fr 1fr auto;gap:6px';row.innerHTML='<input class="seller-input" type="number" min="1" placeholder="Шт." value="'+(q||1)+'"><input class="seller-input" type="number" min="0" placeholder="Цена ₽" value="'+(p||0)+'"><button type="button">×</button>';row.querySelector('button').onclick=function(){row.remove()};document.getElementById('emForcedRows').appendChild(row)}
var q=Number(document.getElementById('sellerProductStock')&&document.getElementById('sellerProductStock').value||1),p=Number(document.getElementById('sellerProductPrice')&&document.getElementById('sellerProductPrice').value||0);add(q,p);document.getElementById('emForcedAdd').onclick=function(){add(1,0)};}
function collect(){var rows=document.querySelectorAll('#emForcedRows>div'),out=[];rows.forEach(function(r){var i=r.querySelectorAll('input'),q=Number(i[0].value),p=Number(i[1].value);if(q>0&&p>=0)out.push({qty:Math.floor(q),price:Math.floor(p)})});return out}
function hookSave(){var fn=window.saveSellerProduct;if(typeof fn!=='function'||fn.__emForced)return;var original=fn;window.saveSellerProduct=async function(e){var opts=collect();var d=document.getElementById('sellerProductDetails');if(d){var clean=String(d.value||'').replace(/<!--EM_PRICES:[\\s\\S]*?-->/g,'').trim();d.value=(clean?clean+'\\n':'')+'<!--EM_PRICES:'+JSON.stringify(opts)+'-->'}var price=document.getElementById('sellerProductPrice'),stock=document.getElementById('sellerProductStock');if(opts[0]){if(price)price.value=opts[0].price;if(stock)stock.value=opts[0].qty}return original.call(this,e)};window.saveSellerProduct.__emForced=true}
window.addEventListener('load',function(){ensureSellerOptions();hookSave();setInterval(function(){ensureSellerOptions();hookSave()},700)});
})();
(function(){
'use strict';
var busy=false;window.checkout=async function(){if(busy)return;var cart=Array.isArray(window.cart)?window.cart:[];if(!cart.length){window.showToast&&window.showToast('Корзина пустая');return}var tg=window.Telegram&&window.Telegram.WebApp,user=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;if(!user||!user.id){window.showToast&&window.showToast('Откройте Mini App из Telegram');return}var btn=document.getElementById('checkoutButton');busy=true;if(btn){btn.disabled=true;btn.textContent='Создаём заказ...'}try{var items=cart.map(function(p){return {product_id:p.id,product_name:p.name,price:Number(p.price||0),quantity:Number(p.quantity||1),seller_id:p.seller_id?String(p.seller_id):null}});var sellerIds=[...new Set(items.map(function(x){return x.seller_id}).filter(Boolean))];var result=await window.supabaseClient.rpc('create_order_with_items',{p_order:{telegram_id:String(user.id),telegram_username:user.username?String(user.username):null,total:cart.reduce(function(s,p){return s+Number(p.price||0)},0),status:'pending',seller_id:sellerIds.length===1?sellerIds[0]:null,seller_status:'pending',buyer_received:false},p_items:items});if(result.error)throw result.error;var order=result.data&&result.data.order;if(!order)throw new Error('Сервер не вернул заказ');window.cart=[];window.saveCart&&window.saveCart();window.updateCart&&window.updateCart();window.closeCart&&window.closeCart();window.showToast&&window.showToast('Заказ №'+order.id+' создан ✅');if(tg&&tg.showAlert)tg.showAlert('✅ Заказ №'+order.id+' оформлен!\\n\\n⏳ Ожидайте, пока продавец свяжется с вами.')}catch(e){console.error('CHECKOUT RPC',e);window.showToast&&window.showToast('Ошибка оформления: '+(e.message||e))}finally{busy=false;if(btn){btn.disabled=false;btn.textContent='⚡ Оформить заказ'}}};
})();