/* EasyMarket stable Telegram compatibility layer v20260917-8. */
(function(){
'use strict';
var API='https://uhmgjcoyxehknkehfbbj.supabase.co/functions/v1/easymarket-api';
var SUPABASE_URL='https://uhmgjcoyxehknkehfbbj.supabase.co';
var SUPABASE_KEY='sb_publishable_7Bn4Azfm58BkIJS_6vSsUw_qbGS4wTH';

if(!window.supabaseClient && window.supabase && typeof window.supabase.createClient==='function'){
  window.supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
}

window.emSecureApi=async function(action,payload){
  var tg=window.Telegram&&window.Telegram.WebApp;
  var initData=tg&&tg.initData||'';
  if(!initData) throw new Error('Откройте Mini App из Telegram');
  var response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:action,payload:payload||{},initData:initData})});
  var data=await response.json().catch(function(){return null;});
  if(!response.ok || !data || data.success===false) throw new Error(data&&data.error||'Ошибка сервера');
  return data;
};

/* buyer-price-options.js remains the single owner of catalog/cart state. */

function install(){
  var modal=document.getElementById('productModal');
  if(modal&&modal.dataset.emGuardInstalled!=='1'){
    modal.dataset.emGuardInstalled='1';
    modal.addEventListener('click',function(e){
      if(e.target!==modal)return;
      e.preventDefault();e.stopPropagation();
      if(typeof window.closeProductModal==='function')window.closeProductModal();
      else{modal.classList.remove('open');document.body.style.overflow='';}
    },true);
  }
}

/* The modal button has an inline handler generated by the catalog script.
   Take ownership at capture time so Telegram/WebView click handling cannot
   swallow it; remove the inline handler before calling the same cart function. */
document.addEventListener('click',function(e){
  var btn=e.target&&e.target.closest&&e.target.closest('#productModal .product-modal-actions .product-buy-now');
  if(!btn)return;
  var code=btn.getAttribute('onclick')||'';
  var m=code.match(/addToCartFromModal\(\s*(\d+)\s*,\s*(\d+(?:\.\d+)?)\s*\)/);
  if(!m)return;
  e.preventDefault();
  e.stopImmediatePropagation();
  btn.removeAttribute('onclick');
  if(typeof window.addToCartFromModal==='function'){
    window.addToCartFromModal(Number(m[1]),Number(m[2]));
  }else{
    window.showToast&&window.showToast('Корзина ещё загружается, попробуйте ещё раз');
  }
},true);

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();

/* Main catalog button: "Оформить". Modal button: "Оформить заказ". */
(function(){
  var style=document.createElement('style');
  style.id='em-order-cta-label';
  style.textContent='.product-buy-now{font-size:13px!important}.product-modal-actions .product-buy-now{font-size:0!important}.product-modal-actions .product-buy-now::after{content:"⚡ Оформить заказ";font-size:13px;font-weight:700}';
  (document.head||document.documentElement).appendChild(style);
})();